// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZWdJyouU20Q269dx8yOx2utAgM_TfMzU',
    appId: '1:1002901530103:web:6b80d74b13cc9b1fd5baf2',
    messagingSenderId: '1002901530103',
    projectId: 'ntrade-173ec',
    authDomain: 'ntrade-173ec.firebaseapp.com',
    storageBucket: 'ntrade-173ec.appspot.com',
    measurementId: 'G-QT2GWK1DXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD46G9P97HOwkYNQdNgZ9JGjKDvvj22kW4',
    appId: '1:1002901530103:android:ee55d6215bd28086d5baf2',
    messagingSenderId: '1002901530103',
    projectId: 'ntrade-173ec',
    storageBucket: 'ntrade-173ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWdJ77r3jYnMsKfm7DcqC9gCAuiMftakQ',
    appId: '1:1002901530103:ios:af4616c0fa7da528d5baf2',
    messagingSenderId: '1002901530103',
    projectId: 'ntrade-173ec',
    storageBucket: 'ntrade-173ec.appspot.com',
    iosBundleId: 'com.example.n1DispositivosMoveis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWdJ77r3jYnMsKfm7DcqC9gCAuiMftakQ',
    appId: '1:1002901530103:ios:3fe37f4f01752bb6d5baf2',
    messagingSenderId: '1002901530103',
    projectId: 'ntrade-173ec',
    storageBucket: 'ntrade-173ec.appspot.com',
    iosBundleId: 'com.example.n1DispositivosMoveis.RunnerTests',
  );
}
